name: CI

on:
  push:
  pull_request:
  schedule:
    - cron:  '0 0 1 * *'

jobs:
  Linux:
    name: Linux

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - name: Script
      run: |
        set -x
        bash -o pipefail -- info.sh
        bash -e -o pipefail -- ipinfo.sh
        bash -e -o pipefail -- typeinfo.sh
        CXX=clang++ bash -e -o pipefail -- typeinfo.sh
    - name: ShellCheck
      run: bash -c 'shopt -s globstar; shellcheck -o avoid-nullary-conditions,check-extra-masked-returns,check-set-e-suppressed,deprecate-which,quote-safe-variables,require-double-brackets -s bash **/*.sh'
      continue-on-error: true

  macOS:
    name: macOS Datatype Information

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-13, macos-14]
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - name: Script
      run: |
        set -x
        bash -e -o pipefail -- typeinfo.sh
